config/routes.rb
Rails.application.routes.draw do

  resources :events, only: [:index, :show]

  resources :registered_applications

  devise_for :users
  resources :users, only: [:show]

  namespace :api, defaults: { format: :json } do
    resources :events, only: [:create]
  end

  get "welcome/index"
  get 'about' => 'welcome#about'
  
  root to: 'welcome#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :registered_application
  has_many :users, through: :registered_applications
  
  validates_presence_of :name
end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
  belongs_to :user
  has_many :events, dependent: :destroy
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :registered_applications, dependent: :destroy
  has_many :events, through: :registered_applications
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token
  
  def create
    registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])
    if registered_application.nil?
      render json: "Unregistered application", status: :unprocessable_entity
    else
      @event = registered_application.events.build(event_params)
        if @event.save
          render json: @event, status: :created
        else
          render json: {error: "missing event name"}, status: :unprocessable_entity
        end
    end
  end

  private
  def event_params
    params.require(:event).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  include Pundit
   
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
 
   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
   end
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  before_action :authenticate_user!, except: [ :index, :show ]

  def index
    @registered_applications = RegisteredApplication.all
  end

  def show
    @registered_application = RegisteredApplication.find(params[:id])
    @events = @registered_application.events(:group => 'name')
  end

  def new
    @registered_application = RegisteredApplication.new
    
  end

  def create
    @registered_application = RegisteredApplication.new( registered_application_params.merge( user_id: current_user.id ) )
   

    if @registered_application.save
      redirect_to @registered_application, notice: "Application was registered successfully."
    else
      flash[:error] = "Error registering application. Please try again."
      render :new
    end
  end

  def edit
    @registered_application = RegisteredApplication.find(params[:id])
    
  end

  def update
    @registered_application = RegisteredApplication.find(params[:id])
    

    if @registered_application.update_attributes( registered_application_params )
      redirect_to @registered_application, notice: "Application updated successfully."
    else
      flash[:error] = "Error updating applcation. Please try again."
      render :edit
    end
  end

  def destroy
    @registered_application = RegisteredApplication.find(params[:id])
    name = @registered_application.name
   

    if @registered_application.destroy
      flash[:notice] = "\"#{name}\" was deleted successfully."
    else
      flash[:error] = "Error deleting application. Please try again."
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

private

  def registered_application_params
    params.require(:registered_application).permit(:name, :url, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @registered_applications = current_user.registered_applications
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
   def my_name
    "Joel Ramsey"
  end
  def form_group_tag(errors, &block)
     if errors.any?
       content_tag :div, capture(&block), class: 'form-group has-error'
     else
       content_tag :div, capture(&block), class: 'form-group'
     end
   end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_event.html.erb
<%= content_tag_for :div, @event, class: "row" do %>
  <div>
    <h5>
      <%= link_to "#{@event.name}", @event, class:'button-space' %>
    </h5>
  </div> 
<% end %>

app/views/events/index.html.erb
<h1>Events#index</h1>
<p>Find me in app/views/events/index.html.erb</p>

app/views/events/show.html.erb
<h1>Events#show</h1>
<p>Find me in app/views/events/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--<script>blocmetrics.report()</script> -->
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
</head>
<body>

  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Blocmetrics", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <% if current_user %>
      <li><%= link_to "My Applications", registered_applications_path %></li>
      <% end %>
      

      <div class="pull-right user-info">
       <% if current_user %>
          
          
          Hello <%= link_to (current_user.name || current_user.email), edit_user_registration_path %>!
          <%= link_to edit_user_registration_path, class: 'btn btn-primary btn-sm' do %>
            <span class="glyphicon glyphicon-user"></span>
          <% end %>
          
          <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-sm' do %>
            <span class="glyphicon glyphicon-log-out"></span>
          <% end %>
        <% else %>
            <%= link_to "Sign In", new_user_session_path %> or
            <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>

    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>

app/views/registered_applications/_form.html.erb
<%= form_for [@registered_application] do |f| %>
  <% if @registered_application.errors.any? %>
    <div class="alert alert-danger">
      <h4>There are <%= pluralize(@registered_application.errors.count, "error") %>.</h4>
      <ul>
        <% @registered_application.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(@registered_application.errors[:name]) do %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter application name" %>
  <% end %>
  <%= form_group_tag(@registered_application.errors[:description]) do %>
    <%= f.label :url %>
    <%= f.text_area :url, rows: 1, class: 'form-control', placeholder: "Enter URL" %>
  <% end %>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/registered_applications/_registered_application.html.erb
<%= content_tag_for :div, registered_application, class: "row" do %>
  <div>
    <h3>
      <%= link_to "#{registered_application.name}", registered_application, class:'button-space' %>
      <% if policy(registered_application).destroy? %>
        <%= link_to "Delete", registered_application, method: :delete, remote: true, class: 'btn btn-xs btn-danger'%>
      <% end %>
    </h3>
  </div> 
<% end %>

app/views/registered_applications/destroy.js.erb
<% if @registered_application.destroyed? %>
  $(<%= dom_id( @registered_application ) %>).fadeOut(900);
<% else %>
  $(<%= dom_id( @registered_application ) %>).prepend("<div class='alert alert-danger'><%= flash[:error] %></div>");
<% end %>

app/views/registered_applications/edit.html.erb
<div class="page-header">
  <h1>Edit Application</h1>
</div>

<%= form_for @registered_application do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :url, "URL" %>
    <%= f.text_field :url %>
  </div>
  <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/registered_applications/index.html.erb
<div align="center">
  <h1>All Applications</h1>
</div>
<div align="right">
  <%= link_to "New Application", new_registered_application_path, class: 'btn btn-success' %>
</div>

<%= render @registered_applications %>

app/views/registered_applications/new.html.erb
<div class="page-header">
  <h1>New Application</h1>
</div>

<%= render partial: 'form', locals: { registerd_application: @registered_application } %>

app/views/registered_applications/show.html.erb
<%= content_tag_for :div, @registered_application do %>
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <div align="center">
    <h1>
      <%= "#{@registered_application.name}" %>
      <br/><%= link_to @registered_application.url, "http://#{@registered_application.url}", :target => '_blank' %>
    </h1>
      <% if policy(@registered_application).edit? %>
        <%= link_to "Edit", edit_registered_application_path, class: 'btn btn-success' %>
        <%= link_to "Delete", registered_application_path(@registered_application), method: :delete, remote: true, class: 'btn btn-danger' %>
      <% end %>
  </div>
  <h1> Events </h1>
  <% @events.group_by(&:name).each do |name, events| %>
    <div>
      <%= name %> <span class="badge"><%= events.count %></span>
    </div>
  <% end %>
</br>
  <div>
    <button class="btn btn-primary" type="button">
    Total Events <span class="badge"><%= @events.count %></span>  
    </button>
    <%= pie_chart @registered_application.events.group(:name).count %>
    <%= line_chart @registered_application.events.group_by_day(:created_at).count %>
  </div>
<% end %>

app/views/users/registered_application.erb
<%= content_tag_for :div, registered_application, class: "row" do %>
  <div>
    <h3>
      <%= link_to "#{registered_application.name}", registered_application, class:'button-space' %>
      <% if policy(registered_application).destroy? %>
        <%= link_to "Delete", registered_application, method: :delete, remote: true, class: 'btn btn-xs btn-danger'%>
      <% end %>
    </h3>
  </div> 

<% end %>

app/views/users/show.html.erb
<h1 class="text-center">My Registered Applications</h1>
  <% @registered_applications.each do | registered_application | %>
    <%= render partial: 'users/registered_application', locals: { registered_application: registered_application } %>
  <% end %>

app/views/welcome/about.html.erb
<h1>About Blocmarks</h1>
<p>created by: <%= my_name %></p>

app/views/welcome/index.html.erb
<br/>
<div class="jumbotron">
  <h1>Blocmetrics</h1>
  <p>Blocmetrics is an analytics service for web sites</p>
  <p>
    
  </p>
</div>

<div class="row jumbotron">
  <div class="col-md-4 ">
    <h2>Tracking</h2>
    <p>Allows a users to track events on their website.</p>
  </div>
  <div class="col-md-4 ">
    <h2>Persistence</h2>
    <p> Provides a server-side API that captures and saves those events to a database.</p>
  </div>
  <div class="col-md-4 ">
    <h2>Analyze</h2>
    <p>Display captured metrics for optimization assessment.</p>
  </div>
</div>